### PR TITLE
fix for issue 189

### PR DESCRIPTION
**Pull request by pohzipohzi**

### CODE REVIEW

**Comment by foxmask** [comment]
i'm afraid I can't accept it, as every potential contributors have alread asked me to handle one of the hacktober issue. Even it is valid. Each guy are waiting for (at least tomorrow) to propose their PR.
Sorry for that.

**Comment by pohzipohzi** [comment]
Hey no worries. I wanted to do #188 before the first part of it got shifted to #189, hence I can't do the PR I initially intended to. Guess I will have to wait a bit

**Comment by pohzipohzi** [comment]
Hi @foxmask. Thanks for reopening the PR. Many of the tests are failing due to the names. Should I rename all the tests to include `_KEY` as well?

**Comment by foxmask** [comment]
yes, it's true, you are right

**Comment by foxmask** [comment]
Thanks !

**Pull request merged**
