### PR TITLE
+ Dash + th

### PR DESCRIPTION
**Pull request by adriancarayol**

### CODE REVIEW

**Comment by foxmask** [comment]
You dont need to add all the dash sources to your fork.
Just push dash in requirements.txt and adjust the templates of the admin you need.

**Comment by adriancarayol** [comment]
A small mistake, I accidentally did the pull request from the mobile!

**Comment by foxmask** [comment]
no problem, i saw, i just gave an advice :)

**Comment by adriancarayol** [comment]
My idea is to modify the dash models, and that each widget contains a trigger

**Pull request closed without merging**
